/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { NewsletterSubscription } from '../models';
/**
 * AdminMarketingNewsletterSubscriptionsApi - axios parameter creator
 * @export
 */
export const AdminMarketingNewsletterSubscriptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new newsletter subscription
         * @param {NewsletterSubscription} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (body: NewsletterSubscription, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling create.');
            }
            const localVarPath = `/newsletter-subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all newsletter subscriptions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findAll: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/newsletter-subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unsubscribe an email from the newsletter
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsubscribe: async (email: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            if (email === null || email === undefined) {
                throw new RequiredError('email','Required parameter email was null or undefined when calling unsubscribe.');
            }
            const localVarPath = `/newsletter-subscriptions/unsubscribe/{email}`
                .replace(`{${"email"}}`, encodeURIComponent(String(email)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminMarketingNewsletterSubscriptionsApi - functional programming interface
 * @export
 */
export const AdminMarketingNewsletterSubscriptionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new newsletter subscription
         * @param {NewsletterSubscription} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(body: NewsletterSubscription, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<NewsletterSubscription>>> {
            const localVarAxiosArgs = await AdminMarketingNewsletterSubscriptionsApiAxiosParamCreator(configuration).create(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get all newsletter subscriptions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<NewsletterSubscription>>>> {
            const localVarAxiosArgs = await AdminMarketingNewsletterSubscriptionsApiAxiosParamCreator(configuration).findAll(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Unsubscribe an email from the newsletter
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsubscribe(email: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await AdminMarketingNewsletterSubscriptionsApiAxiosParamCreator(configuration).unsubscribe(email, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AdminMarketingNewsletterSubscriptionsApi - factory interface
 * @export
 */
export const AdminMarketingNewsletterSubscriptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a new newsletter subscription
         * @param {NewsletterSubscription} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(body: NewsletterSubscription, options?: AxiosRequestConfig): Promise<AxiosResponse<NewsletterSubscription>> {
            return AdminMarketingNewsletterSubscriptionsApiFp(configuration).create(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all newsletter subscriptions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findAll(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<NewsletterSubscription>>> {
            return AdminMarketingNewsletterSubscriptionsApiFp(configuration).findAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unsubscribe an email from the newsletter
         * @param {string} email 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsubscribe(email: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return AdminMarketingNewsletterSubscriptionsApiFp(configuration).unsubscribe(email, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminMarketingNewsletterSubscriptionsApi - object-oriented interface
 * @export
 * @class AdminMarketingNewsletterSubscriptionsApi
 * @extends {BaseAPI}
 */
export class AdminMarketingNewsletterSubscriptionsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new newsletter subscription
     * @param {NewsletterSubscription} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMarketingNewsletterSubscriptionsApi
     */
    public async create(body: NewsletterSubscription, options?: AxiosRequestConfig) : Promise<AxiosResponse<NewsletterSubscription>> {
        return AdminMarketingNewsletterSubscriptionsApiFp(this.configuration).create(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get all newsletter subscriptions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMarketingNewsletterSubscriptionsApi
     */
    public async findAll(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<NewsletterSubscription>>> {
        return AdminMarketingNewsletterSubscriptionsApiFp(this.configuration).findAll(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Unsubscribe an email from the newsletter
     * @param {string} email 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminMarketingNewsletterSubscriptionsApi
     */
    public async unsubscribe(email: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return AdminMarketingNewsletterSubscriptionsApiFp(this.configuration).unsubscribe(email, options).then((request) => request(this.axios, this.basePath));
    }
}
