/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CirclePostReact } from '../models';
import { CirclePostReactDto } from '../models';
/**
 * CirclePostReactsApi - axios parameter creator
 * @export
 */
export const CirclePostReactsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CirclePostReactDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCirclePostReact: async (body: CirclePostReactDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createCirclePostReact.');
            }
            const localVarPath = `/circle-post-reacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} circlePost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCirclePostReact: async (circlePost: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'circlePost' is not null or undefined
            if (circlePost === null || circlePost === undefined) {
                throw new RequiredError('circlePost','Required parameter circlePost was null or undefined when calling deleteCirclePostReact.');
            }
            const localVarPath = `/circle-post-reacts/{_circlePost}`
                .replace(`{${"_circlePost"}}`, encodeURIComponent(String(circlePost)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCirclePostReacts: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/circle-post-reacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CirclePostReactsApi - functional programming interface
 * @export
 */
export const CirclePostReactsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CirclePostReactDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCirclePostReact(body: CirclePostReactDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CirclePostReact>>> {
            const localVarAxiosArgs = await CirclePostReactsApiAxiosParamCreator(configuration).createCirclePostReact(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} circlePost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCirclePostReact(circlePost: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await CirclePostReactsApiAxiosParamCreator(configuration).deleteCirclePostReact(circlePost, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCirclePostReacts(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<CirclePostReact>>>> {
            const localVarAxiosArgs = await CirclePostReactsApiAxiosParamCreator(configuration).getCirclePostReacts(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CirclePostReactsApi - factory interface
 * @export
 */
export const CirclePostReactsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {CirclePostReactDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCirclePostReact(body: CirclePostReactDto, options?: AxiosRequestConfig): Promise<AxiosResponse<CirclePostReact>> {
            return CirclePostReactsApiFp(configuration).createCirclePostReact(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} circlePost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCirclePostReact(circlePost: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return CirclePostReactsApiFp(configuration).deleteCirclePostReact(circlePost, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCirclePostReacts(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<CirclePostReact>>> {
            return CirclePostReactsApiFp(configuration).getCirclePostReacts(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CirclePostReactsApi - object-oriented interface
 * @export
 * @class CirclePostReactsApi
 * @extends {BaseAPI}
 */
export class CirclePostReactsApi extends BaseAPI {
    /**
     * 
     * @param {CirclePostReactDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CirclePostReactsApi
     */
    public async createCirclePostReact(body: CirclePostReactDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<CirclePostReact>> {
        return CirclePostReactsApiFp(this.configuration).createCirclePostReact(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} circlePost 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CirclePostReactsApi
     */
    public async deleteCirclePostReact(circlePost: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return CirclePostReactsApiFp(this.configuration).deleteCirclePostReact(circlePost, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CirclePostReactsApi
     */
    public async getCirclePostReacts(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<CirclePostReact>>> {
        return CirclePostReactsApiFp(this.configuration).getCirclePostReacts(options).then((request) => request(this.axios, this.basePath));
    }
}
