/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CirclePostView } from '../models';
import { CirclePostViewDto } from '../models';
/**
 * CirclePostViewsApi - axios parameter creator
 * @export
 */
export const CirclePostViewsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CirclePostViewDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCirclePostView: async (body: CirclePostViewDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createCirclePostView.');
            }
            const localVarPath = `/circle-post-views`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCirclePostViews: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/circle-post-views`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CirclePostViewsApi - functional programming interface
 * @export
 */
export const CirclePostViewsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CirclePostViewDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCirclePostView(body: CirclePostViewDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CirclePostView>>> {
            const localVarAxiosArgs = await CirclePostViewsApiAxiosParamCreator(configuration).createCirclePostView(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCirclePostViews(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<CirclePostView>>>> {
            const localVarAxiosArgs = await CirclePostViewsApiAxiosParamCreator(configuration).getCirclePostViews(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CirclePostViewsApi - factory interface
 * @export
 */
export const CirclePostViewsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {CirclePostViewDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCirclePostView(body: CirclePostViewDto, options?: AxiosRequestConfig): Promise<AxiosResponse<CirclePostView>> {
            return CirclePostViewsApiFp(configuration).createCirclePostView(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCirclePostViews(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<CirclePostView>>> {
            return CirclePostViewsApiFp(configuration).getCirclePostViews(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CirclePostViewsApi - object-oriented interface
 * @export
 * @class CirclePostViewsApi
 * @extends {BaseAPI}
 */
export class CirclePostViewsApi extends BaseAPI {
    /**
     * 
     * @param {CirclePostViewDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CirclePostViewsApi
     */
    public async createCirclePostView(body: CirclePostViewDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<CirclePostView>> {
        return CirclePostViewsApiFp(this.configuration).createCirclePostView(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CirclePostViewsApi
     */
    public async getCirclePostViews(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<CirclePostView>>> {
        return CirclePostViewsApiFp(this.configuration).getCirclePostViews(options).then((request) => request(this.axios, this.basePath));
    }
}
