/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { User } from '../models';
/**
 * PaymentMobilizerManualPaymentApi - axios parameter creator
 * @export
 */
export const PaymentMobilizerManualPaymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get manually paid mobilizers
         * @param {number} [skip] Number of records to skip
         * @param {number} [limit] Maximum number of records to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManuallyPaidMobilizers: async (skip?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/manual-payment/get-manually-paid-mobilizers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark a mobilizer as manually paid
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markMobilizerAsManuallyPaid: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/manual-payment/mark-mobilizer-as-manually-paid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentMobilizerManualPaymentApi - functional programming interface
 * @export
 */
export const PaymentMobilizerManualPaymentApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get manually paid mobilizers
         * @param {number} [skip] Number of records to skip
         * @param {number} [limit] Maximum number of records to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getManuallyPaidMobilizers(skip?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<User>>>> {
            const localVarAxiosArgs = await PaymentMobilizerManualPaymentApiAxiosParamCreator(configuration).getManuallyPaidMobilizers(skip, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Mark a mobilizer as manually paid
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markMobilizerAsManuallyPaid(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PaymentMobilizerManualPaymentApiAxiosParamCreator(configuration).markMobilizerAsManuallyPaid(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PaymentMobilizerManualPaymentApi - factory interface
 * @export
 */
export const PaymentMobilizerManualPaymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get manually paid mobilizers
         * @param {number} [skip] Number of records to skip
         * @param {number} [limit] Maximum number of records to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getManuallyPaidMobilizers(skip?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<User>>> {
            return PaymentMobilizerManualPaymentApiFp(configuration).getManuallyPaidMobilizers(skip, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark a mobilizer as manually paid
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markMobilizerAsManuallyPaid(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PaymentMobilizerManualPaymentApiFp(configuration).markMobilizerAsManuallyPaid(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentMobilizerManualPaymentApi - object-oriented interface
 * @export
 * @class PaymentMobilizerManualPaymentApi
 * @extends {BaseAPI}
 */
export class PaymentMobilizerManualPaymentApi extends BaseAPI {
    /**
     * 
     * @summary Get manually paid mobilizers
     * @param {number} [skip] Number of records to skip
     * @param {number} [limit] Maximum number of records to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentMobilizerManualPaymentApi
     */
    public async getManuallyPaidMobilizers(skip?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<User>>> {
        return PaymentMobilizerManualPaymentApiFp(this.configuration).getManuallyPaidMobilizers(skip, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Mark a mobilizer as manually paid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentMobilizerManualPaymentApi
     */
    public async markMobilizerAsManuallyPaid(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PaymentMobilizerManualPaymentApiFp(this.configuration).markMobilizerAsManuallyPaid(options).then((request) => request(this.axios, this.basePath));
    }
}
