/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CircleSubscription } from './circle-subscription';
 /**
 * 
 *
 * @export
 * @interface ActiveCircleSubscriptionsByTierDto
 */
export interface ActiveCircleSubscriptionsByTierDto {

    /**
     * @type {Array<CircleSubscription>}
     * @memberof ActiveCircleSubscriptionsByTierDto
     */
    STARTER: Array<CircleSubscription>;

    /**
     * @type {Array<CircleSubscription>}
     * @memberof ActiveCircleSubscriptionsByTierDto
     */
    ADVOCATE: Array<CircleSubscription>;

    /**
     * @type {Array<CircleSubscription>}
     * @memberof ActiveCircleSubscriptionsByTierDto
     */
    CHANGER: Array<CircleSubscription>;

    /**
     * @type {number}
     * @memberof ActiveCircleSubscriptionsByTierDto
     */
    TOTAL: number;
}
