/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Ambassador
 */
export interface Ambassador {

    /**
     * @type {string}
     * @memberof Ambassador
     */
    id: string;

    /**
     * @type {string}
     * @memberof Ambassador
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof Ambassador
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof Ambassador
     */
    country: string;

    /**
     * @type {string}
     * @memberof Ambassador
     */
    description: string;

    /**
     * @type {string}
     * @memberof Ambassador
     */
    category: string;

    /**
     * @type {string}
     * @memberof Ambassador
     */
    image?: string;
}
