/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Challenge
 */
export interface Challenge {

    /**
     * @type {string}
     * @memberof Challenge
     */
    id: string;

    /**
     * @type {string}
     * @memberof Challenge
     */
    circleName: string;

    /**
     * @type {string}
     * @memberof Challenge
     */
    challenge: string;

    /**
     * @type {string}
     * @memberof Challenge
     */
    userEmail: string;

    /**
     * @type {string}
     * @memberof Challenge
     */
    status: ChallengeStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ChallengeStatusEnum {
    Resolved = 'Resolved',
    NotResolved = 'NotResolved'
}

