/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PublicCircleProfileDTO } from './public-circle-profile-dto';
import { PublicUserProfile } from './public-user-profile';
 /**
 * 
 *
 * @export
 * @interface CirclePost
 */
export interface CirclePost {

    /**
     * @type {string}
     * @memberof CirclePost
     */
    id: string;

    /**
     * @type {string}
     * @memberof CirclePost
     */
    title: string;

    /**
     * @type {string}
     * @memberof CirclePost
     */
    summary: string;

    /**
     * @type {string}
     * @memberof CirclePost
     */
    description: string;

    /**
     * @type {string}
     * @memberof CirclePost
     */
    circle: string;

    /**
     * @type {string}
     * @memberof CirclePost
     */
    user: string;

    /**
     * @type {string}
     * @memberof CirclePost
     */
    file: string;

    /**
     * @type {Array<string>}
     * @memberof CirclePost
     */
    files: Array<string>;

    /**
     * @type {boolean}
     * @memberof CirclePost
     */
    isPublic?: boolean;

    /**
     * @type {PublicCircleProfileDTO}
     * @memberof CirclePost
     */
    circle: PublicCircleProfileDTO;

    /**
     * @type {PublicUserProfile}
     * @memberof CirclePost
     */
    user: PublicUserProfile;

    /**
     * @type {Date}
     * @memberof CirclePost
     */
    createdAt: Date;
}
