/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CircleBoard
 */
export interface CircleBoard {

    /**
     * @type {string}
     * @memberof CircleBoard
     */
    id: string;

    /**
     * @type {string}
     * @memberof CircleBoard
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof CircleBoard
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof CircleBoard
     */
    country: string;

    /**
     * @type {string}
     * @memberof CircleBoard
     */
    role: string;

    /**
     * @type {string}
     * @memberof CircleBoard
     */
    image?: string;
}
