/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CircleWork
 */
export interface CircleWork {

    /**
     * @type {string}
     * @memberof CircleWork
     */
    id: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    title: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    imageUrl: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    description: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    tag: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    circle: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    audioUrl: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    linkedin: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    instagram: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    website: string;

    /**
     * @type {string}
     * @memberof CircleWork
     */
    lang: string;
}
