/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CirclePostReactDto
 */
export interface CirclePostReactDto {

    /**
     * @type {string}
     * @memberof CirclePostReactDto
     */
    circlePost: string;

    /**
     * @type {string}
     * @memberof CirclePostReactDto
     */
    user: string;
}
