/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CirclePost } from './circle-post';
import { PublicUserProfile } from './public-user-profile';
 /**
 * 
 *
 * @export
 * @interface CirclePostReact
 */
export interface CirclePostReact {

    /**
     * @type {string}
     * @memberof CirclePostReact
     */
    id: string;

    /**
     * @type {string}
     * @memberof CirclePostReact
     */
    user: string;

    /**
     * @type {string}
     * @memberof CirclePostReact
     */
    circlePost: string;

    /**
     * @type {PublicUserProfile}
     * @memberof CirclePostReact
     */
    user: PublicUserProfile;

    /**
     * @type {CirclePost}
     * @memberof CirclePostReact
     */
    circlePost: CirclePost;
}
