/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CircleEvent } from './circle-event';
import { PublicUserProfile } from './public-user-profile';
 /**
 * 
 *
 * @export
 * @interface CircleEventSubscription
 */
export interface CircleEventSubscription {

    /**
     * @type {string}
     * @memberof CircleEventSubscription
     */
    id: string;

    /**
     * @type {string}
     * @memberof CircleEventSubscription
     */
    user: string;

    /**
     * @type {string}
     * @memberof CircleEventSubscription
     */
    event: string;

    /**
     * @type {PublicUserProfile}
     * @memberof CircleEventSubscription
     */
    user: PublicUserProfile;

    /**
     * @type {CircleEvent}
     * @memberof CircleEventSubscription
     */
    event: CircleEvent;
}
