/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CircleworkBody
 */
export interface CircleworkBody {

    /**
     * @type {Array<Blob>}
     * @memberof CircleworkBody
     */
    image?: Array<Blob> | null;

    /**
     * @type {Array<Blob>}
     * @memberof CircleworkBody
     */
    audio?: Array<Blob> | null;
}
