/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateStoryDTO
 */
export interface CreateStoryDTO {

    /**
     * @type {Blob}
     * @memberof CreateStoryDTO
     */
    photo?: Blob | null;

    /**
     * @type {Blob}
     * @memberof CreateStoryDTO
     */
    cover?: Blob | null;

    /**
     * @type {Date}
     * @memberof CreateStoryDTO
     */
    date: Date;

    /**
     * @type {string}
     * @memberof CreateStoryDTO
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateStoryDTO
     */
    writer: string;

    /**
     * @type {string}
     * @memberof CreateStoryDTO
     */
    description?: string;

    /**
     * @type {string}
     * @memberof CreateStoryDTO
     */
    subTitle?: string;

    /**
     * @type {string}
     * @memberof CreateStoryDTO
     */
    text1?: string;

    /**
     * @type {string}
     * @memberof CreateStoryDTO
     */
    text2?: string;
}
