/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateUpdatePollDtoVotes } from './create-update-poll-dto-votes';
import { CreateUpdatePollDtoVotesPerOption } from './create-update-poll-dto-votes-per-option';
 /**
 * 
 *
 * @export
 * @interface CreateUpdatePollDto
 */
export interface CreateUpdatePollDto {

    /**
     * @type {string}
     * @memberof CreateUpdatePollDto
     */
    question: string;

    /**
     * @type {Array<string>}
     * @memberof CreateUpdatePollDto
     */
    options: Array<string>;

    /**
     * @type {Array<CreateUpdatePollDtoVotes>}
     * @memberof CreateUpdatePollDto
     */
    votes?: Array<CreateUpdatePollDtoVotes>;

    /**
     * @type {Array<CreateUpdatePollDtoVotesPerOption>}
     * @memberof CreateUpdatePollDto
     */
    votesPerOption?: Array<CreateUpdatePollDtoVotesPerOption>;
}
