/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateThreadDto
 */
export interface CreateThreadDto {

    /**
     * @type {string}
     * @memberof CreateThreadDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateThreadDto
     */
    content: string;

    /**
     * @type {string}
     * @memberof CreateThreadDto
     */
    circle: string;
}
