/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateCircleDTO
 */
export interface CreateCircleDTO {

    /**
     * @type {boolean}
     * @memberof CreateCircleDTO
     */
    main: boolean;

    /**
     * @type {boolean}
     * @memberof CreateCircleDTO
     */
    global: boolean;

    /**
     * @type {boolean}
     * @memberof CreateCircleDTO
     */
    isActive: boolean;

    /**
     * @type {string}
     * @memberof CreateCircleDTO
     */
    user: string;

    /**
     * @type {string}
     * @memberof CreateCircleDTO
     */
    urlName: string;

    /**
     * @type {string}
     * @memberof CreateCircleDTO
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateCircleDTO
     */
    goal: string;

    /**
     * @type {number}
     * @memberof CreateCircleDTO
     */
    subscriptionGoal: number;

    /**
     * @type {string}
     * @memberof CreateCircleDTO
     */
    description: string;

    /**
     * @type {string}
     * @memberof CreateCircleDTO
     */
    type: string;

    /**
     * @type {Blob}
     * @memberof CreateCircleDTO
     */
    avatar?: Blob | null;

    /**
     * @type {Blob}
     * @memberof CreateCircleDTO
     */
    cover?: Blob | null;

    /**
     * @type {Blob}
     * @memberof CreateCircleDTO
     */
    video?: Blob | null;

    /**
     * @type {boolean}
     * @memberof CreateCircleDTO
     */
    isPayoutEnabled?: boolean;

    /**
     * @type {Array<string>}
     * @memberof CreateCircleDTO
     */
    supporters?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof CreateCircleDTO
     */
    mobilizers?: Array<string>;

    /**
     * @type {number}
     * @memberof CreateCircleDTO
     */
    activeCampaigners?: number;
}
