/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Entry
 */
export interface Entry {

    /**
     * @type {string}
     * @memberof Entry
     */
    imageUrl: string;

    /**
     * @type {string}
     * @memberof Entry
     */
    body: string;

    /**
     * @type {string}
     * @memberof Entry
     */
    quoteeName: string;

    /**
     * @type {string}
     * @memberof Entry
     */
    quoteePosition: string;

    /**
     * @type {string}
     * @memberof Entry
     */
    quoteeOrganization: string;
}
