/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FirstPartyAnalyticsDto
 */
export interface FirstPartyAnalyticsDto {

    /**
     * @type {string}
     * @memberof FirstPartyAnalyticsDto
     */
    iSO3: string;

    /**
     * @type {string}
     * @memberof FirstPartyAnalyticsDto
     */
    name: string;

    /**
     * @type {number}
     * @memberof FirstPartyAnalyticsDto
     */
    usersCount: number;
}
