/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Circle } from './circle';
 /**
 * 
 *
 * @export
 * @interface GroupedCircles
 */
export interface GroupedCircles {

    /**
     * @type {string}
     * @memberof GroupedCircles
     */
    id: string;

    /**
     * @type {string}
     * @memberof GroupedCircles
     */
    name: string;

    /**
     * @type {Array<Circle>}
     * @memberof GroupedCircles
     */
    circles: Array<Circle>;
}
