/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface I18nTranslateRequestDto
 */
export interface I18nTranslateRequestDto {

    /**
     * @type {string}
     * @memberof I18nTranslateRequestDto
     */
    originalText: string;

    /**
     * @type {any}
     * @memberof I18nTranslateRequestDto
     */
    targetLanguage: any;
}
