/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200Info } from './inline-response200-info';
 /**
 * 
 *
 * @export
 * @interface InlineResponse503
 */
export interface InlineResponse503 {

    /**
     * @type {string}
     * @memberof InlineResponse503
     * @example error
     */
    status?: string;

    /**
     * @type {{ [key: string]: InlineResponse200Info; }}
     * @memberof InlineResponse503
     * @example {"database":{"status":"up"}}
     */
    info?: { [key: string]: InlineResponse200Info; } | null;

    /**
     * @type {{ [key: string]: InlineResponse200Info; }}
     * @memberof InlineResponse503
     * @example {"redis":{"status":"down","message":"Could not connect"}}
     */
    error?: { [key: string]: InlineResponse200Info; } | null;

    /**
     * @type {{ [key: string]: InlineResponse200Info; }}
     * @memberof InlineResponse503
     * @example {"database":{"status":"up"},"redis":{"status":"down","message":"Could not connect"}}
     */
    details?: { [key: string]: InlineResponse200Info; };
}
