/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InviteUserDtoClimateWins } from './invite-user-dto-climate-wins';
 /**
 * 
 *
 * @export
 * @interface InviteUserDto
 */
export interface InviteUserDto {

    /**
     * Role is required and must be \"MOBILIZER\" or \"SUPPORTER\"
     *
     * @type {string}
     * @memberof InviteUserDto
     * @example SUPPORTER
     */
    role: InviteUserDtoRoleEnum;

    /**
     * @type {boolean}
     * @memberof InviteUserDto
     */
    hasPassword: boolean;

    /**
     * @type {boolean}
     * @memberof InviteUserDto
     */
    privateAccount: boolean;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    isActive: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    customerId: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    circleName: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    affiliateOrganization: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    firstname: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    lastname: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    email: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    avatar: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    video: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    cover: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    facebook: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    instagram: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    linkedin: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    tiktok: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    slug?: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    twitter: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    website: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    country: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    city: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    description: string;

    /**
     * @type {Array<string>}
     * @memberof InviteUserDto
     */
    skills: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof InviteUserDto
     */
    cares: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof InviteUserDto
     */
    tags: Array<string>;

    /**
     * @type {boolean}
     * @memberof InviteUserDto
     */
    status: boolean;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    referralId: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    whatsapp?: string;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    audio: string;

    /**
     * @type {InviteUserDtoClimateWins}
     * @memberof InviteUserDto
     */
    climateWins: InviteUserDtoClimateWins;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    mobilizerMainTopic: InviteUserDtoMobilizerMainTopicEnum;

    /**
     * @type {string}
     * @memberof InviteUserDto
     */
    mobilizerType: InviteUserDtoMobilizerTypeEnum;

    /**
     * @type {number}
     * @memberof InviteUserDto
     */
    referredVisitors: number;

    /**
     * @type {number}
     * @memberof InviteUserDto
     */
    descriptionSize: number;

    /**
     * @type {InviteUserDtoClimateWins}
     * @memberof InviteUserDto
     */
    bio: InviteUserDtoClimateWins;

    /**
     * @type {number}
     * @memberof InviteUserDto
     */
    order?: number;

    /**
     * @type {boolean}
     * @memberof InviteUserDto
     */
    featured: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum InviteUserDtoRoleEnum {
    SUPPORTER = 'SUPPORTER',
    MOBILIZER = 'MOBILIZER',
    ADMIN = 'ADMIN',
    LEADADMIN = 'LEAD-ADMIN',
    SUPERMOBILIZER = 'SUPER-MOBILIZER',
    AMBASSADOR = 'AMBASSADOR',
    PARTNER = 'PARTNER',
    ORGANIZATION = 'ORGANIZATION',
    TRIAL = 'TRIAL',
    TRIALSUPPORTER = 'TRIAL-SUPPORTER'
}
/**
 * @export
 * @enum {string}
 */
export enum InviteUserDtoMobilizerMainTopicEnum {
    ForestLand = 'Forest & Land',
    Governance = 'Governance',
    Power = 'Power',
    CircularEconomy = 'Circular Economy',
    Finance = 'Finance'
}
/**
 * @export
 * @enum {string}
 */
export enum InviteUserDtoMobilizerTypeEnum {
    CAMPAIGNER = 'CAMPAIGNER',
    RESEARCHER = 'RESEARCHER',
    POLICYCHANGER = 'POLICY_CHANGER',
    EDUCATOR = 'EDUCATOR'
}

