/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LinkedinPositionDetails
 */
export interface LinkedinPositionDetails {

    /**
     * @type {any}
     * @memberof LinkedinPositionDetails
     */
    title: any;

    /**
     * @type {any}
     * @memberof LinkedinPositionDetails
     */
    description: any;

    /**
     * @type {Date}
     * @memberof LinkedinPositionDetails
     */
    dateStarted: Date;
}
