/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MediumFacadeDTO
 */
export interface MediumFacadeDTO {

    /**
     * @type {string}
     * @memberof MediumFacadeDTO
     */
    title: string;

    /**
     * @type {string}
     * @memberof MediumFacadeDTO
     */
    description: string;

    /**
     * @type {string}
     * @memberof MediumFacadeDTO
     */
    url: string;

    /**
     * @type {Blob}
     * @memberof MediumFacadeDTO
     */
    image?: Blob | null;

    /**
     * @type {string}
     * @memberof MediumFacadeDTO
     */
    displayLocation: string;
}
