/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MyInvoiceListParams
 */
export interface MyInvoiceListParams {

    /**
     * @type {any}
     * @memberof MyInvoiceListParams
     */
    collectionMethod?: any;

    /**
     * @type {any}
     * @memberof MyInvoiceListParams
     */
    created?: any;

    /**
     * @type {string}
     * @memberof MyInvoiceListParams
     */
    customer?: string;

    /**
     * @type {any}
     * @memberof MyInvoiceListParams
     */
    dueDate?: any;

    /**
     * @type {Array<string>}
     * @memberof MyInvoiceListParams
     */
    expand?: Array<string>;

    /**
     * @type {any}
     * @memberof MyInvoiceListParams
     */
    status?: any;

    /**
     * @type {string}
     * @memberof MyInvoiceListParams
     */
    subscription?: string;
}
