/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrganizationStatsDto
 */
export interface OrganizationStatsDto {

    /**
     * @type {number}
     * @memberof OrganizationStatsDto
     */
    certifications: number;

    /**
     * @type {number}
     * @memberof OrganizationStatsDto
     */
    nps: number;

    /**
     * @type {number}
     * @memberof OrganizationStatsDto
     */
    champions: number;

    /**
     * @type {number}
     * @memberof OrganizationStatsDto
     */
    events: number;

    /**
     * @type {number}
     * @memberof OrganizationStatsDto
     */
    orgUserId: number;
}
