/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrganizationDto
 */
export interface OrganizationDto {

    /**
     * @type {string}
     * @memberof OrganizationDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof OrganizationDto
     */
    organizationBanner: string;

    /**
     * @type {string}
     * @memberof OrganizationDto
     */
    organizationName: string;

    /**
     * @type {string}
     * @memberof OrganizationDto
     */
    organizationAccent: string;
}
