/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {

    /**
     * @type {string}
     * @memberof PaymentMethod
     */
    id: string;

    /**
     * @type {string}
     * @memberof PaymentMethod
     */
    brand: string;

    /**
     * @type {string}
     * @memberof PaymentMethod
     */
    last4: string;

    /**
     * @type {number}
     * @memberof PaymentMethod
     */
    expMonth: number;

    /**
     * @type {number}
     * @memberof PaymentMethod
     */
    expYear: number;
}
