/* tslint:disable */
/* eslint-disable */
/**
 * hero-circle-api
 * The Hero Circle API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VictoryDto
 */
export interface VictoryDto {

    /**
     * @type {string}
     * @memberof VictoryDto
     */
    description: string;

    /**
     * @type {string}
     * @memberof VictoryDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof VictoryDto
     */
    summary: string;

    /**
     * @type {Date}
     * @memberof VictoryDto
     */
    date: Date;

    /**
     * @type {string}
     * @memberof VictoryDto
     */
    file?: string;

    /**
     * @type {Array<string>}
     * @memberof VictoryDto
     */
    files?: Array<string>;

    /**
     * @type {boolean}
     * @memberof VictoryDto
     */
    isPublic?: boolean;

    /**
     * @type {string}
     * @memberof VictoryDto
     */
    video?: string;

    /**
     * @type {boolean}
     * @memberof VictoryDto
     */
    isPinned?: boolean;
}
